services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./site
    ports:
      - "5173:5173"
    volumes:
      - ./site:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
