# Исходный образ
FROM node:18

WORKDIR /app

COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем всё остальное
COPY . .

# Указываем порт
EXPOSE 5173

# Команда по умолчанию для запуска dev-сервера
CMD ["npm", "run", "dev"]